spring.application.name=estoque_senai
# Configurações do Banco de Dados
spring.jpa.database=postgresql
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# Informações para conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/db_estoque_senai
spring.datasource.username=postgres
spring.datasource.password=postgres